default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: swrpg_sheet_development
  username: rminer

test:
  <<: *default
  database: swrpg_sheet_test
  username: rminer

#production:
  #<<: *default
  #database: swrpg_sheet_production
